version: '3'

services:
    nodejs-api-mongodb:
        build: .
        restart: always
        container_name: nodejs-api-products
        volumes: 
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - '3001:3001'
        environment:
            - DB_URL=nodejs-db-mongo
            - DB_PORT=27017
            - API_PORT=3001
        depends_on: 
            - nodejs-db-mongo
        networks: 
            - nodejs-api          

    nodejs-db-mongo:
        image: mongo
        restart: always
        ports:
        - 27017:27017
        volumes: 
            - mongo-express-data:/data
        networks: 
            - nodejs-api
volumes: 
    mongo-express-data:

networks: 
    nodejs-api:
        driver: bridge