version: '3'

services:
    nodejs-api-products:
        build: .
        restart: always
        container_name: nodejs-api-products
        volumes: 
            - .:/home/node/api
            - /home/node/api/node_modules
        ports:
            - '3001:3001'
        environment:
            - DB_URL=mongo
            - DB_PORT=27017
            - API_PORT=3001
        depends_on: 
            - mongo
        networks: 
            - bridge          

    mongo:
        image: mongo
        restart: always
        ports:
        - 27017:27017
        volumes: 
            - mongo-express-data:/data
        networks: 
            - bridge
volumes: 
    mongo-express-data:

networks: 
    bridge:
        driver: bridge